default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/engsi
  username: postgres
  password: c3po

test:
  <<: *default
  database: db/engsi_test
  username: postgres
  password: c3po

production:
  <<: *default
  database: db/engsi_production
  username: postgres
  password: c3po